AllCops:
  TargetRubyVersion: 2.7.5
  NewCops: enable

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: err

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

